name: Create release in Sentry
on:
  release:
    types: [prereleased, released]
jobs:
  sentry-cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create a Sentry.io release
      uses: tclindner/sentry-releases-action@v1.2.0
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: lensvol
        SENTRY_PROJECT: blackconnect
      with:
        tagName: ${{ github.ref }}
        environment: production
